all: grep run
grep:
    cat s.py | grep import


run:
    python s.py


help:
    @ echo "all: import the !signal! and run"
    @ echo "run: run the program"
    @ echo "grep: pipe to grep import to show what has been imported"
